/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsgateway;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author risnawan
 */
public class F_RCrud extends javax.swing.JFrame {

    /**
     * Creates new form F_RCrud
     */
    private koneksi kon;
    public F_RCrud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_hp = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btn_simpan6 = new javax.swing.JButton();
        btn_kembali6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 153, 255));
        jLabel31.setText("Form Warga");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 153, 255));
        jLabel32.setText("Nama");

        txt_nama.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(51, 153, 255));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 153, 255));
        jLabel33.setText("Nomor HandPhone");

        txt_hp.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_hp.setForeground(new java.awt.Color(51, 153, 255));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 153, 255));
        jLabel34.setText("Alamat");

        btn_simpan6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_simpan6.setForeground(new java.awt.Color(51, 153, 255));
        btn_simpan6.setText("Simpan");
        btn_simpan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan6ActionPerformed(evt);
            }
        });

        btn_kembali6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_kembali6.setForeground(new java.awt.Color(51, 153, 255));
        btn_kembali6.setText("Kembali");
        btn_kembali6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembali6ActionPerformed(evt);
            }
        });

        txt_alamat.setColumns(20);
        txt_alamat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_alamat.setForeground(new java.awt.Color(51, 153, 255));
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btn_kembali6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_simpan6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_hp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel31)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txt_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan6)
                            .addComponent(btn_kembali6))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembali6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembali6ActionPerformed
        // TODO add your handling code here:
        new F_Registrasi().show();
        this.dispose();
    }//GEN-LAST:event_btn_kembali6ActionPerformed

    private void btn_simpan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan6ActionPerformed
        // TODO add your handling code here:
        try{
            simpan(txt_nama.getText(), txt_hp.getText(), txt_alamat.getText());
            JOptionPane.showMessageDialog(null, "Berhasil");
            new F_RCrud().show();
            this.dispose();
        }catch(ClassNotFoundException es){
            JOptionPane.showMessageDialog(null, "gagal");
        }
    }//GEN-LAST:event_btn_simpan6ActionPerformed

    public void simpan(String nama, String hp, String alamat) throws ClassNotFoundException {
        kon = new koneksi();        
        try {
            Statement stasql = (Statement)kon.Connect().createStatement();
            int runkueri = stasql.executeUpdate("insert into warga (id, nama, alamat, nomor) VALUES (NULL, '"+nama+"','"+alamat+"', '"+hp+"')"); //Database pesan, field no_tujuan dan isi_pesan
            stasql.close();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_RCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_RCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_RCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_RCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_RCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_kembali1;
    private javax.swing.JButton btn_kembali2;
    private javax.swing.JButton btn_kembali3;
    private javax.swing.JButton btn_kembali4;
    private javax.swing.JButton btn_kembali5;
    private javax.swing.JButton btn_kembali6;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_simpan1;
    private javax.swing.JButton btn_simpan2;
    private javax.swing.JButton btn_simpan3;
    private javax.swing.JButton btn_simpan4;
    private javax.swing.JButton btn_simpan5;
    private javax.swing.JButton btn_simpan6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_baudrate;
    private javax.swing.JTextField txt_baudrate1;
    private javax.swing.JTextField txt_baudrate2;
    private javax.swing.JTextField txt_baudrate3;
    private javax.swing.JTextField txt_baudrate4;
    private javax.swing.JTextField txt_baudrate5;
    private javax.swing.JTextField txt_comport;
    private javax.swing.JTextField txt_comport1;
    private javax.swing.JTextField txt_comport2;
    private javax.swing.JTextField txt_comport3;
    private javax.swing.JTextField txt_comport4;
    private javax.swing.JTextField txt_comport5;
    private javax.swing.JTextField txt_hp;
    private javax.swing.JTextField txt_manu;
    private javax.swing.JTextField txt_manu1;
    private javax.swing.JTextField txt_manu2;
    private javax.swing.JTextField txt_manu3;
    private javax.swing.JTextField txt_manu4;
    private javax.swing.JTextField txt_manu5;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_model1;
    private javax.swing.JTextField txt_model2;
    private javax.swing.JTextField txt_model3;
    private javax.swing.JTextField txt_model4;
    private javax.swing.JTextField txt_model5;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
