/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsgateway;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public final class F_SendMessage extends javax.swing.JFrame {

    /**
     * Creates new form F_SendMessage
     */
    private koneksi kon;
    private String notujuan,isipesan;
    private String kueri;
    private String stradmin;
    DefaultListModel model = new DefaultListModel();
    
    public F_SendMessage(String namaadmin) {
        stradmin = namaadmin;
        initComponents();
        kon = new koneksi();
        
        lbl_namaadmin.setText(stradmin);
        txt_notujuan.setText("");
        txt_isipesan.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_judul = new javax.swing.JLabel();
        lbl_notujuan = new javax.swing.JLabel();
        txt_notujuan = new javax.swing.JTextField();
        lbl_isipesan = new javax.swing.JLabel();
        btn_kirim = new javax.swing.JToggleButton();
        btn_kembali = new javax.swing.JButton();
        lbl_namaadmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_isipesan = new javax.swing.JTextArea();
        pBc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        btn_hapus = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_judul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_judul.setForeground(new java.awt.Color(51, 153, 255));
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("Buat SMS Baru");

        lbl_notujuan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_notujuan.setForeground(new java.awt.Color(51, 153, 255));
        lbl_notujuan.setText("Nomor Tujuan");

        txt_notujuan.setForeground(new java.awt.Color(51, 153, 255));
        txt_notujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_notujuanKeyTyped(evt);
            }
        });

        lbl_isipesan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_isipesan.setForeground(new java.awt.Color(51, 153, 255));
        lbl_isipesan.setText("Isi Pesan");

        btn_kirim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_kirim.setForeground(new java.awt.Color(51, 153, 255));
        btn_kirim.setText("Kirim");
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });

        btn_kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(51, 153, 255));
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        lbl_namaadmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_namaadmin.setForeground(new java.awt.Color(51, 153, 255));
        lbl_namaadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_namaadmin.setText("Nama Admin");

        txt_isipesan.setColumns(20);
        txt_isipesan.setForeground(new java.awt.Color(51, 153, 255));
        txt_isipesan.setRows(5);
        jScrollPane1.setViewportView(txt_isipesan);

        pBc.setBackground(new java.awt.Color(0, 51, 51));
        pBc.setBorder(javax.swing.BorderFactory.createTitledBorder("Broadcast"));
        pBc.setForeground(new java.awt.Color(51, 153, 255));
        pBc.setToolTipText("Broadcast");

        jList1.setForeground(new java.awt.Color(51, 153, 255));
        jScrollPane2.setViewportView(jList1);

        btn_hapus.setForeground(new java.awt.Color(51, 153, 255));
        btn_hapus.setText("hapus nomor");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBcLayout = new javax.swing.GroupLayout(pBc);
        pBc.setLayout(pBcLayout);
        pBcLayout.setHorizontalGroup(
            pBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBcLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBcLayout.setVerticalGroup(
            pBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_hapus)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btn_tambah.setForeground(new java.awt.Color(51, 153, 255));
        btn_tambah.setText("tambah nomor");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jCheckBox1.setForeground(new java.awt.Color(51, 153, 255));
        jCheckBox1.setText("Broadcast");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_namaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_notujuan)
                    .addComponent(txt_notujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambah))
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_isipesan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(btn_kirim)
                        .addGap(19, 19, 19)
                        .addComponent(btn_kembali)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_namaadmin))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_notujuan)
                                .addGap(3, 3, 3)
                                .addComponent(txt_notujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_tambah))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jCheckBox1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_isipesan)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kirim)
                    .addComponent(btn_kembali))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        // TODO add your handling code here:
        try {
            if (!jCheckBox1.isSelected()){
                SendMessage app = new SendMessage();
                try {
                    for (int i = 0; i < model.getSize(); i++){
                        app.doIt(String.valueOf(model.get(i)), txt_isipesan.getText());
                        simpanPesan();
                    }        
                } catch (Exception e){
                    e.printStackTrace();
                }
            }
            //PANGGIL FUNGSI SENDMESSAGE
            F_Main a = new F_Main(stradmin);
            a.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
           Logger.getLogger(F_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_kirimActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        F_Main a = new F_Main(stradmin);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        //        try{
//            int a = Integer.parseInt(txt_notujuan.getText());
//        }catch(Exception es){
//            JOptionPane.showMessageDialog(null,"Masukkan hanya angka saja");
//        }
        jList1.setModel(model);
        if (!txt_notujuan.getText().isEmpty())
            model.addElement(txt_notujuan.getText());
        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()){
            pBc.setVisible(true);
            btn_tambah.setVisible(true);
        } else {
            pBc.setVisible(false);
            btn_tambah.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if(jList1.getSelectedIndex()> -1){
            model.remove(jList1.getSelectedIndex());
        }else {
            JOptionPane.showMessageDialog(null,"sorot nomor terlebih dahulu");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_notujuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_notujuanKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_notujuanKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btn_tambah.setVisible(false);
        pBc.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    public void simpanPesan () throws ClassNotFoundException {
        
        notujuan = txt_notujuan.getText(); //VARIABEL UNTUK SENDMESSAGE
        isipesan = txt_isipesan.getText(); //VARIABEL UNTUK SENDMESSAGE
        
        try {
            Statement stasql = (Statement)kon.Connect().createStatement();
            int runkueri = stasql.executeUpdate("insert into pesan (id_pesan, no_tujuan, isi_pesan) VALUES (NULL, '"+notujuan+"','"+isipesan+"')"); //Database pesan, field no_tujuan dan isi_pesan
//            JOptionPane.showMessageDialog(null,"Pesan berhasil disimpan");
            stasql.close();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_SendMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_SendMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_SendMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_SendMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new F_SendMessage().setVisible(true);
                F_Login b = new F_Login();
                b.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JToggleButton btn_kirim;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_isipesan;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_namaadmin;
    private javax.swing.JLabel lbl_notujuan;
    private javax.swing.JPanel pBc;
    private javax.swing.JTextArea txt_isipesan;
    private javax.swing.JTextField txt_notujuan;
    // End of variables declaration//GEN-END:variables
}
